# <img src="https://img.icons8.com/dusk/64/000000/mind-map.png" style="height:50px;display:inline"> Simplifying Machine Learning with PyCaret: A Low-code Approach for Beginners and Experts!
---

#### <a href="https://hossainlab.github.io">Md. Jubayer Hossain</a>
[Founder & Executive Director, CHIRAL Bangladesh]() <br/>
[Instructor, cBLAST]()

## Lecture 02 -Understand Your Data With Descriptive Statistics 
---

### <img src="https://img.icons8.com/bubbles/50/000000/checklist.png" style="height:50px;display:inline"> Agenda
---
You must understand your data in order to get the best results. In this lecture you will discover 7 recipes that you can use in Python to better understand your machine learning data. After completing this lesson you will know how to: 

1. Take a peek at your raw data.
2. Review the dimensions of your dataset.
3. Review the data types of attributes in your data.
4. Summarize the distribution of instances across classes in your dataset.
5. Summarize your data using descriptive statistics.
6. Understand the relationships in your data using correlations.
7. Review the skew of the distributions of each attribute.

In [1]:
# import packages 
import numpy as np 
import pandas as pd

In [2]:
# import data 
data = pd.read_csv("../data/Heart_Attack.csv")

## Peek at Your Data
There is no substitute for looking at the raw data. Looking at the raw data can reveal insights that you cannot get any other way. It can also plant seeds that may later grow into ideas on how to better pre-process and handle the data for machine learning tasks. You can review the first few rows of your data using the `head()` function on the Pandas `DataFrame`.

In [4]:
# examine first few rows
data.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Outcome
0,64,Male,66.0,160.0,83.0,160.0,1.80,0.012,Negative
1,21,Male,94.0,98.0,46.0,296.0,6.75,1.060,Positive
2,55,Male,64.0,160.0,77.0,270.0,1.99,0.003,Negative
3,64,Male,NaN,120.0,55.0,270.0,13.87,0.122,Positive
4,55,Male,64.0,112.0,65.0,300.0,1.08,0.003,Negative

## Dimensions of Your Data
You must have a very good handle on how much data you have, both in terms of rows and columns.

- Too many rows and algorithms may take too long to train. Too few and perhaps you do not have enough data to train the algorithms.
- Too many features and some algorithms can be distracted or suffer poor performance due to the curse of dimensionality.

You can review the shape and `size` of your dataset by printing the shape property on the Pandas `DataFrame`.

In [4]:
data.shape

(1319, 9)

The results are listed in rows then columns. You can see that the dataset has 1319 rows and 9 columns.

## Data Type For Each Attribute
The type of each attribute is important. `Strings` may need to be converted to `floating` point values or integers to represent `categorical` or `ordinal` values. You can get an idea of the types of attributes by peeking at the raw data, as above. You can also list the data types used by the DataFrame to characterize each attribute using the dtypes property.

In [5]:
data.dtypes

Age                           int64
Gender                       object
Heart rate                  float64
Systolic blood pressure     float64
Diastolic blood pressure    float64
Blood sugar                 float64
CK-MB                       float64
Troponin                    float64
Outcome                      object
dtype: object

In [6]:
# select numeric variables 
num_df = data.select_dtypes(exclude = 'object')
num_df.head()

,Age,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin
0,64,66.0,160.0,83.0,160.0,1.80,0.012
1,21,94.0,98.0,46.0,296.0,6.75,1.060
2,55,64.0,160.0,77.0,270.0,1.99,0.003
3,64,NaN,120.0,55.0,270.0,13.87,0.122
4,55,64.0,112.0,65.0,300.0,1.08,0.003

In [7]:
# select categorical variables 
cat_df = data.select_dtypes(include = 'object')
cat_df.head()

  Gender   Outcome
0   Male  Negative
1   Male  Positive
2   Male  Negative
3   Male  Positive
4   Male  Negative

## Descriptive Statistics
Descriptive statistics can give you great insight into the shape of each attribute. Often you can create more summaries than you have time to review. The `describe()` function on the Pandas

DataFrame lists 8 statistical properties of each attribute. They are:
- Count.
- Mean.
- Standard Deviation.
- Minimum Value.
- 25th Percentile.
- 50th Percentile (Median).
- 75th Percentile.
- Maximum Value.

In [8]:
num_df.describe()

,Age,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin
count,1319.000000,1311.000000,1317.000000,1318.000000,1317.000000,1318.000000,1319.000000
mean,56.191812,78.357742,127.097950,72.263278,146.569248,15.285140,0.360942
std,13.647315,51.776068,26.059092,14.037634,74.880060,46.342996,1.154568
min,14.000000,20.000000,42.000000,38.000000,35.000000,0.321000,0.001000
25%,47.000000,64.000000,110.000000,62.000000,98.000000,1.660000,0.006000
50%,58.000000,74.000000,124.000000,72.000000,116.000000,2.850000,0.014000
75%,65.000000,85.000000,143.000000,81.000000,169.000000,5.807500,0.085500
max,103.000000,1111.000000,223.000000,154.000000,541.000000,300.000000,10.300000

In [9]:
cat_df.describe()

       Gender   Outcome
count    1311      1313
unique      2         2
top      Male  Positive
freq      864       807

## Class Distribution (Classification Only)
On classification problems you need to know how balanced the class values are. Highly imbalanced problems (a lot more observations for one class than another) are common and may need special handling in the data preparation stage of your project. You can quickly get an idea of the distribution of the class attribute in Pandas.

In [10]:
data.groupby('Outcome').size()

Outcome
Negative    506
Positive    807
dtype: int64

You can see that there are nearly double the number of observations with class 0 (no onset of caridiovascular disease) than there are with class 1 (onset of caridiovascular disease).

## Correlations Between Attributes
Correlation refers to the relationship between two variables and how they may or may not change together. The most common method for calculating correlation is Pearson’s Correlation Coefficient, that assumes a normal distribution of the attributes involved. A correlation of -1 or 1 shows a full negative or positive correlation respectively. Whereas a value of 0 shows no correlation at all. Some machine learning algorithms like linear and logistic regression can suffer poor performance if there are highly correlated attributes in your dataset. As such, it is a good idea to review all of the pairwise correlations of the attributes in your dataset. You can use the `corr()` function on the Pandas DataFrame to calculate a correlation matrix.

In [11]:
# correlation: Pearson’s by default 
num_df.corr(method="pearson")

,Age,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin
Age,1.000000,-0.023535,0.016106,0.002559,-0.003579,0.018315,0.088800
Heart rate,-0.023535,1.000000,0.011496,0.107894,-0.018656,-0.013189,0.011090
Systolic blood pressure,0.016106,0.011496,1.000000,0.584811,0.020159,-0.015865,0.035248
Diastolic blood pressure,0.002559,0.107894,0.584811,1.000000,-0.024792,-0.023680,0.043496
Blood sugar,-0.003579,-0.018656,0.020159,-0.024792,1.000000,0.038816,0.021364
CK-MB,0.018315,-0.013189,-0.015865,-0.023680,0.038816,1.000000,-0.015908
Troponin,0.088800,0.011090,0.035248,0.043496,0.021364,-0.015908,1.000000

The matrix lists all attributes across the top and down the side, to give correlation between all pairs of attributes (twice, because the matrix is symmetrical). You can see the diagonal line through the matrix from the top left to bottom right corners of the matrix shows perfect correlation of each attribute with itself.

## Skew of Univariate Distributions
Skew refers to a distribution that is assumed Gaussian (normal or bell curve) that is shifted or squashed in one direction or another. Many machine learning algorithms assume a Gaussian/normal distribution. Knowing that an attribute has a skew may allow you to perform data preparation
to correct the skew and later improve the accuracy of your models. You can calculate the skew of each attribute using the `skew()` function on the Pandas DataFrame.

In [12]:
num_df.skew()

Age                         -0.239219
Heart rate                  18.203483
Systolic blood pressure      0.683183
Diastolic blood pressure     0.490315
Blood sugar                  1.938347
CK-MB                        4.976071
Troponin                     5.799107
dtype: float64

The skew result show a positive (right) or negative (left) skew. Values closer to zero show less skew.

## <img src="https://img.icons8.com/dusk/64/000000/prize.png" style="height:50px;display:inline"> Credits
---
* Icons from <a href="https://icons8.com/">Icon8.com</a> - https://icons8.com
* Datasets from <a href="https://www.kaggle.com/">Kaggle</a> - https://www.kaggle.com/
* Examples and code snippets were taken from <a href="https://machinelearningmastery.com/machine-learning-with-python/">"Machine Learning Mastery With Python"</a>