# <img src="https://img.icons8.com/dusk/64/000000/mind-map.png" style="height:50px;display:inline"> Simplifying Machine Learning with PyCaret: A Low-code Approach for Beginners and Experts!
---

#### <a href="https://hossainlab.github.io">Md. Jubayer Hossain</a>
[Founder & Executive Director, CHIRAL Bangladesh]() <br/>
[Instructor, cBLAST]()


## Lecture 04 - Prepare Your Data for Machine Learning
---

### <img src="https://img.icons8.com/bubbles/50/000000/checklist.png" style="height:50px;display:inline"> Agenda
---
Many machine learning algorithms make assumptions about your data. It is often a very good idea to prepare your data in such way to best expose the structure of the problem to the machine learning algorithms that you intend to use. In this chapter you will discover how to prepare your data for machine learning in Python using scikit-learn. After completing this lesson you will know how to:

1. Rescale data.
2. Standardize data.
3. Normalize data.
4. Binarize data.

## Why Data Pre-processing
You almost always need to pre-process your data. It is a required step. A difficulty is that different algorithms make different assumptions about your data and may require different transforms. Further, when you follow all of the rules and prepare your data, sometimes algorithms
can deliver better results without pre-processing.

Generally, I would recommend creating many different views and transforms of your data, then exercise a handful of algorithms on each view of your dataset. This will help you to flush out which data transforms might be better at exposing the structure of your problem in general.

## Data Transformation 
In this lecture you will work through 4 different data pre-processing techniques for machine learning. The Cardiovascular Disease dataset is used in each techniques. Each technique follows the same structure:

- Load the dataset
- Split the dataset into the input and output variables for machine learning
- Apply a pre-processing transform to the input variables
- Summarize the data to show the change

The `scikit-learn` library provides two standard idioms for transforming data. Each are useful in different circumstances. The transforms are calculated in such a way that they can be applied to your training data and any samples of data you may have in the future. The scikit-learn
documentation has some information on how to use various different pre-processing methods:

- Fit and Multiple Transform.
- Combined Fit-And-Transform.

In [2]:
# Import necessary packages
import pandas as pd

In [3]:
# import data 
df = pd.read_csv("../data/Heart_Attack.csv")
df.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Outcome
0,64,Male,66.0,160.0,83.0,160.0,1.80,0.012,Negative
1,21,Male,94.0,98.0,46.0,296.0,6.75,1.060,Positive
2,55,Male,64.0,160.0,77.0,270.0,1.99,0.003,Negative
3,64,Male,NaN,120.0,55.0,270.0,13.87,0.122,Positive
4,55,Male,64.0,112.0,65.0,300.0,1.08,0.003,Negative

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1319 non-null   int64
 1   Gender                    1311 non-null   object
 2   Heart rate                1311 non-null   float64
 3   Systolic blood pressure   1317 non-null   float64
 4   Diastolic blood pressure  1318 non-null   float64
 5   Blood sugar               1317 non-null   float64
 6   CK-MB                     1318 non-null   float64
 7   Troponin                  1319 non-null   float64
 8   Outcome                   1313 non-null   object
dtypes: float64(6), int64(1), object(2)
memory usage: 92.9+ KB

In [5]:
df.isnull().sum()

Age                         0
Gender                      8
Heart rate                  8
Systolic blood pressure     2
Diastolic blood pressure    1
Blood sugar                 2
CK-MB                       1
Troponin                    0
Outcome                     6
dtype: int64

## Encoding Categorical Variables

In [10]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
label_encoder = LabelEncoder()
df["Gender"] = label_encoder.fit_transform(df["Gender"])
df.head()

,Age,Gender,Heart rate,Systolic blood pressure,Diastolic blood pressure,Blood sugar,CK-MB,Troponin,Outcome
0,64,1,66.0,160.0,83.0,160.0,1.80,0.012,Negative
1,21,1,94.0,98.0,46.0,296.0,6.75,1.060,Positive
2,55,1,64.0,160.0,77.0,270.0,1.99,0.003,Negative
3,64,1,NaN,120.0,55.0,270.0,13.87,0.122,Positive
4,55,1,64.0,112.0,65.0,300.0,1.08,0.003,Negative

In [11]:
onehot_encoder = OneHotEncoder(sparse_output=False)
encoded_outcome = onehot_encoder.fit_transform(df[["Outcome"]])

## Rescale Data
When your data is comprised of attributes with varying scales, many machine learning algorithms
can benefit from rescaling the attributes to all have the same scale. Often this is referred to
as normalization and attributes are often rescaled into the range between `0` and `1`. This is
useful for optimization algorithms used in the core of machine learning algorithms like `gradient
descent`. It is also useful for algorithms that weight inputs like `regression` and `neural networks`
and algorithms that use distance measures like `k-Nearest Neighbors`. You can rescale your data
using scikit-learn using the `MinMaxScaler` class.

In [7]:
df.head()

,patientid,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,103368,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,119250,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,119372,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,132514,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,146211,31,1,1,199,0,0,2,136,0,5.3,3,2,1

In [11]:
# Rescale data (between 0 and 1)
from sklearn.preprocessing import MinMaxScaler

# separate array into input and output components
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)

print(rescaledX[0:5,:])

[[0.         0.55       1.         0.66666667 0.72641509 0.
  0.         0.5        0.58015267 0.         0.85483871 1.
  1.        ]
 [0.00160627 0.33333333 1.         0.         0.         0.38039867
  0.         0.5        0.33587786 0.         0.59677419 0.33333333
  0.33333333]
 [0.00161861 0.48333333 1.         0.66666667 0.36792453 0.2358804
  0.         0.         1.         1.         0.80645161 0.33333333
  0.        ]
 [0.00294777 0.38333333 1.         0.         0.41509434 0.49003322
  1.         0.5        0.6259542  0.         0.51612903 0.66666667
  0.66666667]
 [0.00433305 0.18333333 1.         0.33333333 0.99056604 0.
  0.         1.         0.49618321 0.         0.85483871 1.
  0.66666667]]

After rescaling you can see that all of the values are in the range between 0 and 1.

## Standardize Data
Standardization is a useful technique to transform attributes with a Gaussian distribution and
differing means and standard deviations to a standard Gaussian distribution with a mean of
`0` and a standard deviation of `1`. It is most suitable for techniques that assume a Gaussian
distribution in the input variables and work better with rescaled data, such as linear regression,
logistic regression and linear discriminate analysis. You can standardize data using scikit-learn
with the `StandardScaler` class

In [12]:
df.head()

,patientid,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,103368,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,119250,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,119372,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,132514,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,146211,31,1,1,199,0,0,2,136,0,5.3,3,2,1

In [13]:
# Standardize data (0 mean, 1 stdev)
from sklearn.preprocessing import StandardScaler

# separate array into input and output components
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
scaler = StandardScaler().fit(X)
rescaledX = scaler.fit_transform(X)

print(rescaledX[0:5,:])

[[-1.70855459  0.21046388  0.55424682  1.07066333  0.64283287 -2.35271743
  -0.64842466  0.32738429  0.04456713 -0.99600797  1.50724524  1.45535031
   1.81967847]
 [-1.70306755 -0.51759105  0.55424682 -1.02867653 -1.92809795 -0.62281703
  -0.64842466  0.32738429 -0.89184003 -0.99600797  0.57695462 -0.53828025
  -0.22720395]
 [-1.7030254  -0.01355302  0.55424682  1.07066333 -0.62593818 -1.2800281
  -0.64842466 -0.9717597   1.65401693  1.00400803  1.33281575 -0.53828025
  -1.25064516]
 [-1.698485   -0.34957837  0.55424682 -1.02867653 -0.45899462 -0.12424311
   1.5421992   0.32738429  0.22014347 -0.99600797  0.2862388   0.45853503
   0.79623726]
 [-1.69375285 -1.02162908  0.55424682  0.0209934   1.57771681 -2.35271743
  -0.64842466  1.62652828 -0.27732283 -0.99600797  1.50724524  1.45535031
   0.79623726]]

The values for each attribute now have a mean value of 0 and a standard deviation of 1.

## Normalize Data
Normalizing in scikit-learn refers to rescaling each observation (row) to have a length of 1 (called a unit norm or a vector with the length of 1 in linear algebra). This pre-processing method can be useful for sparse datasets (lots of zeros) with attributes of varying scales when using algorithms that weight input values such as neural networks and algorithms that use distance measures such as `k-Nearest Neighbors`. You can normalize data in Python with `scikit-learn`
using the `Normalizer` class

In [14]:
df.head()

,patientid,age,gender,chestpain,restingBP,serumcholestrol,fastingbloodsugar,restingrelectro,maxheartrate,exerciseangia,oldpeak,slope,noofmajorvessels,target
0,103368,53,1,2,171,0,0,1,147,0,5.3,3,3,1
1,119250,40,1,0,94,229,0,1,115,0,3.7,1,1,0
2,119372,49,1,2,133,142,0,0,202,1,5.0,1,0,0
3,132514,43,1,0,138,295,1,1,153,0,3.2,2,2,1
4,146211,31,1,1,199,0,0,2,136,0,5.3,3,2,1

In [16]:
# Normalize data (length of 1)
from sklearn.preprocessing import Normalizer

# separate array into input and output components
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
scaler = Normalizer().fit(X)
normalizedX = scaler.fit_transform(X)

print(normalizedX[0:5,:])

[[9.99997487e-01 5.12729924e-04 9.67414951e-06 1.93482990e-05
  1.65427957e-03 0.00000000e+00 0.00000000e+00 9.67414951e-06
  1.42209998e-03 0.00000000e+00 5.12729924e-05 2.90224485e-05
  2.90224485e-05]
 [9.99997324e-01 3.35428872e-04 8.38572179e-06 0.00000000e+00
  7.88257848e-04 1.92033029e-03 0.00000000e+00 8.38572179e-06
  9.64358006e-04 0.00000000e+00 3.10271706e-05 8.38572179e-06
  8.38572179e-06]
 [9.99997155e-01 4.10480352e-04 8.37715004e-06 1.67543001e-05
  1.11416096e-03 1.18955531e-03 0.00000000e+00 0.00000000e+00
  1.69218431e-03 8.37715004e-06 4.18857502e-05 8.37715004e-06
  0.00000000e+00]
 [9.99996260e-01 3.24492802e-04 7.54634424e-06 0.00000000e+00
  1.04139550e-03 2.22617155e-03 7.54634424e-06 7.54634424e-06
  1.15459067e-03 0.00000000e+00 2.41483016e-05 1.50926885e-05
  1.50926885e-05]
 [9.99998618e-01 2.12022058e-04 6.83942123e-06 6.83942123e-06
  1.36104482e-03 0.00000000e+00 0.00000000e+00 1.36788425e-05
  9.30161287e-04 0.00000000e+00 3.62489325e-05 2.05182637e-05
  1.36788425e-05]]

The rows are normalized to length 1.

## Binarize Data (Make Binary)
You can transform your data using a binary threshold. All values above the threshold are marked 1 and all equal to or below are marked as 0. This is called binarizing your data or thresholding your data. It can be useful when you have probabilities that you want to make crisp values. It is also useful when feature engineering and you want to add new features that indicate
something meaningful. You can create new binary attributes in Python using scikit-learn with the `Binarizer` class

In [1]:
# Binarization
from sklearn.preprocessing import Binarizer

# separate array into input and output components
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)

print(binaryX[0:5,:])

NameError: name 'df' is not defined

You can see that all values equal or less than 0 are marked 0 and all of those above 0 are marked 1.