# Module 04 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.9 - Combine Data
## Agenda
- Merging Dataframes
- Concatenating Dataframes

### 4.9.1 Merging Dataframes
![](../img/db_joins.jpg)

In [18]:
#conventional import
import pandas as pd

In [19]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])
staff_df = staff_df.set_index('Name')
staff_df

                 Role
Name
Kelly  Director of HR
Sally  Course liasion
James          Grader

In [20]:
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])
student_df = student_df.set_index('Name')
student_df

            School
Name
James     Business
Mike           Law
Sally  Engineering

### 4.9.1.1 Outer Join
FULL (OUTER) JOIN: Returns all records when there is a match in either left or right table
![](../img/img_fulljoin.gif)

In [4]:
pd.merge(staff_df, student_df, how='outer', on = 'Name')

                 Role       School
Name
James          Grader     Business
Kelly  Director of HR          NaN
Mike              NaN          Law
Sally  Course liasion  Engineering

### Explanation:

The `pd.merge()` function merges two DataFrames, `staff_df` and `student_df`, based on their indexes.

- `staff_df, student_df`:  
  These are the two DataFrames to be merged.

- `how='outer'`:  
  Specifies an outer join, meaning all rows from both DataFrames are included, even if they don't have a match in the other DataFrame. Missing values are filled with `NaN`.

- `on = 'Name'`:  
  Indicates that the merge should be done based on the `Name` column

This creates a new DataFrame with rows from both `staff_df` and `student_df`, where rows with the same index are combined, and rows with no corresponding match in the other DataFrame have `NaN` values in the resulting DataFrame.

### 4.9.2 Inner Join
(INNER) JOIN: Returns records that have matching values in both tables
![](../img/img_innerjoin.gif)

In [5]:
pd.merge(staff_df, student_df, how='inner', on = 'Name')

                 Role       School
Name
Sally  Course liasion  Engineering
James          Grader     Business

### 4.9.3 Left Join
LEFT (OUTER) JOIN: Returns all records from the left table, and the matched records from the right table
![](../img/img_leftjoin.gif)

In [6]:
pd.merge(staff_df, student_df, how='left', on = 'Name')

                 Role       School
Name
Kelly  Director of HR          NaN
Sally  Course liasion  Engineering
James          Grader     Business

## Right Join
RIGHT (OUTER) JOIN: Returns all records from the right table, and the matched records from the left table
![](../img/img_rightjoin.gif)

In [7]:
pd.merge(staff_df, student_df, how='right', on = 'Name')

                 Role       School
Name
James          Grader     Business
Mike              NaN          Law
Sally  Course liasion  Engineering

In [12]:
pd.merge(staff_df, student_df, how='right', on = 'Name')

    Name            Role       School
0  James          Grader     Business
1   Mike             NaN          Law
2  Sally  Course liasion  Engineering

In [21]:
# rename student_df column name
student_df = student_df.reset_index(drop=False)

In [22]:
student_df.rename(columns={'Name': 'student_name'}, inplace=True)

In [23]:
student_df

  student_name       School
0        James     Business
1         Mike          Law
2        Sally  Engineering

In [24]:
# error will be occured because 'Name' column is not common now
pd.merge(staff_df, student_df, how='right', on = 'Name')

KeyError: 'Name'

In [25]:
pd.merge(staff_df, student_df, how='right', left_on = 'Name', right_on = 'student_name')

             Role student_name       School
0          Grader        James     Business
1             NaN         Mike          Law
2  Course liasion        Sally  Engineering

## 4.9.2 Concatenating Dataframes

In [26]:
# Creating two sample DataFrames
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})

In [27]:
df1

   A  B
0  1  3
1  2  4

In [28]:
df2

   A  B
0  5  7
1  6  8

### 4.9.1 Row concatenation (Vertical Concatenation)

In [29]:
# Concatenating along rows
result = pd.concat([df1, df2], axis=0)
result

   A  B
0  1  3
1  2  4
0  5  7
1  6  8

### 4.9.2 Column Concatenation (Horizontal Concatenation)

In [30]:
# Concatenating along columns
result = pd.concat([df1, df2], axis=1)
result

   A  B  A  B
0  1  3  5  7
1  2  4  6  8

*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*