# Module 04 - Data Wrangling with Pandas

---

#### <a href="linkedin.com/in/tasmim-rahman-adib-403074221">Tasmim Rahman Adib</a>

# Lecture 4.6 - Summarize Data
## Agenda
- Information about Dataframe
- Descriptive Statistics
- Summarizing Categorical Data
- Custom Summary Function

### 4.6.1 Information about Dataframe

In [37]:
#conventional importing
import pandas as pd

In [38]:
pulse_df = pd.read_csv("../data/pulse.txt", sep = '\t')

In [39]:
pulse_df

,Height,Weight,Age,Gender,Smokes,Alcohol,Exercise,Ran,Pulse1,Pulse2,Year
0,173,57.0,18,2,2,1,2,2,86.0,88.0,93
1,179,58.0,19,2,2,1,2,1,82.0,150.0,93
2,167,62.0,18,2,2,1,1,1,96.0,176.0,93
3,195,84.0,18,1,2,1,1,2,71.0,73.0,93
4,173,64.0,18,2,2,1,3,2,90.0,88.0,93
...,...,...,...,...,...,...,...,...,...,...,...
103,163,47.0,23,2,1,1,3,1,71.0,125.0,98
104,161,43.0,19,2,2,2,3,2,90.0,89.0,98
105,182,60.0,22,1,2,1,3,2,86.0,84.0,98
106,170,65.0,18,1,2,1,1,2,69.0,64.0,98
107,185,85.0,19,1,2,1,2,2,75.0,68.0,98

In [40]:
pulse_df.shape

(108, 11)

In [43]:
# getting basic information
pulse_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Height    108 non-null    int64
 1   Weight    108 non-null    float64
 2   Age       108 non-null    int64
 3   Gender    108 non-null    int64
 4   Smokes    108 non-null    int64
 5   Alcohol   108 non-null    int64
 6   Exercise  108 non-null    int64
 7   Ran       108 non-null    int64
 8   Pulse1    107 non-null    float64
 9   Pulse2    107 non-null    float64
 10  Year      108 non-null    int64
dtypes: float64(3), int64(8)
memory usage: 9.4 KB

### 4.6.2 Descriptive Statistics

In [44]:
data = {
    'Age': [25, 35, 45, 32, 40, 38],
    'Salary': [50000, 80000, 70000, 72000, 68000, 75000],
    'Profession': ["Business", "Engineer", "Engineer", "Business", "Doctor", "Engineer"]
}

In [45]:
df = pd.DataFrame(data)

In [46]:
# basic statistics on each column
df.describe()

             Age        Salary
count   6.000000      6.000000
mean   35.833333  69166.666667
std     6.911343  10284.292230
min    25.000000  50000.000000
25%    32.750000  68500.000000
50%    36.500000  71000.000000
75%    39.500000  74250.000000
max    45.000000  80000.000000

In [47]:
# individual column statistics
df['Age'].mean()

np.float64(35.833333333333336)

### 4.6.3 Summarizing Categorical Data

In [48]:
# Count occurrences of each category in a column
df['Profession'].value_counts()

Profession
Engineer    3
Business    2
Doctor      1
Name: count, dtype: int64

In [49]:
pulse_df['Age'].value_counts()

Age
19    27
20    27
18    23
21    10
22     6
23     6
26     2
28     2
34     1
41     1
25     1
45     1
24     1
Name: count, dtype: int64

In [50]:
# to get proportions instead of raw counts
pulse_df['Age'].value_counts(normalize = True)

Age
19    0.250000
20    0.250000
18    0.212963
21    0.092593
22    0.055556
23    0.055556
26    0.018519
28    0.018519
34    0.009259
41    0.009259
25    0.009259
45    0.009259
24    0.009259
Name: proportion, dtype: float64

### 4.6.4 Apply Custom Summary Function

In [51]:
df

   Age  Salary Profession
0   25   50000   Business
1   35   80000   Engineer
2   45   70000   Engineer
3   32   72000   Business
4   40   68000     Doctor
5   38   75000   Engineer

In [52]:
# Apply custom lambda to a DataFrame
df['Salary'].apply(lambda x: x * 1.1)  # Increases salary by 10%

0    55000.0
1    88000.0
2    77000.0
3    79200.0
4    74800.0
5    82500.0
Name: Salary, dtype: float64

*Copyright &copy; 2024  [Md. Jubayer Hossain](https://hossainlab.github.io/) &  [Center for Bioinformatics Learning Advancement and Systematic Training (cBLAST)](https://www.cblast.du.ac.bd/). All rights reserved*